// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActionsByRoundID = `-- name: GetActionsByRoundID :many
SELECT round_id, action_number, player_id, action_type, tile_left, tile_right, side, resulting_left_end, resulting_right_end, created_at FROM actions
WHERE round_id = $1
ORDER BY action_number
`

func (q *Queries) GetActionsByRoundID(ctx context.Context, roundID pgtype.UUID) ([]Action, error) {
	rows, err := q.db.Query(ctx, getActionsByRoundID, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.RoundID,
			&i.ActionNumber,
			&i.PlayerID,
			&i.ActionType,
			&i.TileLeft,
			&i.TileRight,
			&i.Side,
			&i.ResultingLeftEnd,
			&i.ResultingRightEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesByPlayerID = `-- name: GetGamesByPlayerID :many
SELECT games.game_id, games.lobby_id, games.final_scores, games.team_winner, games.game_state, games.created_at FROM games
JOIN game_players ON game_players.game_id = games.game_id
WHERE game_players.player_id = $1
ORDER BY games.created_at DESC
LIMIT $2 OFFSET $3
`

type GetGamesByPlayerIDParams struct {
	PlayerID string
	Limit    int32
	Offset   int32
}

func (q *Queries) GetGamesByPlayerID(ctx context.Context, arg GetGamesByPlayerIDParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, getGamesByPlayerID, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.GameID,
			&i.LobbyID,
			&i.FinalScores,
			&i.TeamWinner,
			&i.GameState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHandsByRoundID = `-- name: GetHandsByRoundID :many
SELECT round_id, player_id, tiles, created_at FROM round_hands
WHERE round_id = $1
`

func (q *Queries) GetHandsByRoundID(ctx context.Context, roundID pgtype.UUID) ([]RoundHand, error) {
	rows, err := q.db.Query(ctx, getHandsByRoundID, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoundHand
	for rows.Next() {
		var i RoundHand
		if err := rows.Scan(
			&i.RoundID,
			&i.PlayerID,
			&i.Tiles,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoundByID = `-- name: GetRoundByID :one
SELECT round_id, game_id, round_number, starting_player_id, player_order, winner_team_id, reason, scores, created_at, action_count FROM rounds
WHERE round_id = $1
`

func (q *Queries) GetRoundByID(ctx context.Context, roundID pgtype.UUID) (Round, error) {
	row := q.db.QueryRow(ctx, getRoundByID, roundID)
	var i Round
	err := row.Scan(
		&i.RoundID,
		&i.GameID,
		&i.RoundNumber,
		&i.StartingPlayerID,
		&i.PlayerOrder,
		&i.WinnerTeamID,
		&i.Reason,
		&i.Scores,
		&i.CreatedAt,
		&i.ActionCount,
	)
	return i, err
}

const getRoundsByGameID = `-- name: GetRoundsByGameID :many
SELECT round_id, game_id, round_number, starting_player_id, player_order, winner_team_id, reason, scores, created_at, action_count FROM rounds
WHERE game_id = $1
ORDER BY round_number
`

func (q *Queries) GetRoundsByGameID(ctx context.Context, gameID pgtype.UUID) ([]Round, error) {
	rows, err := q.db.Query(ctx, getRoundsByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.RoundID,
			&i.GameID,
			&i.RoundNumber,
			&i.StartingPlayerID,
			&i.PlayerOrder,
			&i.WinnerTeamID,
			&i.Reason,
			&i.Scores,
			&i.CreatedAt,
			&i.ActionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAction = `-- name: InsertAction :exec
INSERT INTO actions (round_id, action_number, player_id, action_type, tile_left, tile_right, side, resulting_left_end, resulting_right_end)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (round_id, action_number) DO NOTHING
`

type InsertActionParams struct {
	RoundID           pgtype.UUID
	ActionNumber      int32
	PlayerID          string
	ActionType        string
	TileLeft          pgtype.Int4
	TileRight         pgtype.Int4
	Side              pgtype.Text
	ResultingLeftEnd  pgtype.Int4
	ResultingRightEnd pgtype.Int4
}

func (q *Queries) InsertAction(ctx context.Context, arg InsertActionParams) error {
	_, err := q.db.Exec(ctx, insertAction,
		arg.RoundID,
		arg.ActionNumber,
		arg.PlayerID,
		arg.ActionType,
		arg.TileLeft,
		arg.TileRight,
		arg.Side,
		arg.ResultingLeftEnd,
		arg.ResultingRightEnd,
	)
	return err
}

const upsertGame = `-- name: UpsertGame :exec
INSERT INTO games (game_id, lobby_id, final_scores, team_winner, game_state)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (game_id) DO UPDATE
SET lobby_id = $2, final_scores = $3, team_winner = $4, game_state = $5
`

type UpsertGameParams struct {
	GameID      pgtype.UUID
	LobbyID     pgtype.UUID
	FinalScores []byte
	TeamWinner  string
	GameState   string
}

func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) error {
	_, err := q.db.Exec(ctx, upsertGame,
		arg.GameID,
		arg.LobbyID,
		arg.FinalScores,
		arg.TeamWinner,
		arg.GameState,
	)
	return err
}

const upsertGamePlayer = `-- name: UpsertGamePlayer :exec
INSERT INTO game_players (game_id, player_id, team_id)
VALUES ($1, $2, $3)
ON CONFLICT (game_id, player_id) DO NOTHING
`

type UpsertGamePlayerParams struct {
	GameID   pgtype.UUID
	PlayerID string
	TeamID   string
}

func (q *Queries) UpsertGamePlayer(ctx context.Context, arg UpsertGamePlayerParams) error {
	_, err := q.db.Exec(ctx, upsertGamePlayer, arg.GameID, arg.PlayerID, arg.TeamID)
	return err
}

const upsertHand = `-- name: UpsertHand :exec
INSERT INTO round_hands (round_id, player_id, tiles)
VALUES ($1, $2, $3)
ON CONFLICT (round_id, player_id) DO NOTHING
`

type UpsertHandParams struct {
	RoundID  pgtype.UUID
	PlayerID string
	Tiles    []byte
}

func (q *Queries) UpsertHand(ctx context.Context, arg UpsertHandParams) error {
	_, err := q.db.Exec(ctx, upsertHand, arg.RoundID, arg.PlayerID, arg.Tiles)
	return err
}

const upsertRound = `-- name: UpsertRound :exec
INSERT INTO rounds (round_id, game_id, round_number, starting_player_id, player_order, winner_team_id, reason, scores, action_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (round_id) DO UPDATE
SET game_id = $2, round_number = $3, starting_player_id = $4, player_order = $5, winner_team_id = $6, reason = $7, scores = $8, action_count = $9
`

type UpsertRoundParams struct {
	RoundID          pgtype.UUID
	GameID           pgtype.UUID
	RoundNumber      int32
	StartingPlayerID string
	PlayerOrder      []string
	WinnerTeamID     string
	Reason           string
	Scores           []byte
	ActionCount      int32
}

func (q *Queries) UpsertRound(ctx context.Context, arg UpsertRoundParams) error {
	_, err := q.db.Exec(ctx, upsertRound,
		arg.RoundID,
		arg.GameID,
		arg.RoundNumber,
		arg.StartingPlayerID,
		arg.PlayerOrder,
		arg.WinnerTeamID,
		arg.Reason,
		arg.Scores,
		arg.ActionCount,
	)
	return err
}
