// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             pgtype.UUID
	Email          string
	HashedPassword string
	DisplayName    string
}
