// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	RoundID           pgtype.UUID
	ActionNumber      int32
	PlayerID          string
	ActionType        string
	TileLeft          pgtype.Int4
	TileRight         pgtype.Int4
	Side              pgtype.Text
	ResultingLeftEnd  pgtype.Int4
	ResultingRightEnd pgtype.Int4
	CreatedAt         pgtype.Timestamptz
}

type Game struct {
	GameID      pgtype.UUID
	LobbyID     pgtype.UUID
	FinalScores []byte
	TeamWinner  string
	GameState   string
	CreatedAt   pgtype.Timestamptz
}

type GamePlayer struct {
	GameID   pgtype.UUID
	PlayerID string
	TeamID   string
}

type Round struct {
	RoundID          pgtype.UUID
	GameID           pgtype.UUID
	RoundNumber      int32
	StartingPlayerID string
	PlayerOrder      []string
	WinnerTeamID     string
	Reason           string
	Scores           []byte
	CreatedAt        pgtype.Timestamptz
	ActionCount      int32
}

type RoundHand struct {
	RoundID   pgtype.UUID
	PlayerID  string
	Tiles     []byte
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Email          string
	HashedPassword string
	DisplayName    string
}
