// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuest = `-- name: CreateGuest :one
INSERT INTO users (id, display_name, type)
VALUES ( $1, $2, $3)
RETURNING id, display_name, type
`

type CreateGuestParams struct {
	ID          pgtype.UUID
	DisplayName string
	Type        string
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (User, error) {
	row := q.db.QueryRow(ctx, createGuest, arg.ID, arg.DisplayName, arg.Type)
	var i User
	err := row.Scan(&i.ID, &i.DisplayName, &i.Type)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, type FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.DisplayName, &i.Type)
	return i, err
}
