// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: game.proto

package game

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_PlayTile_FullMethodName  = "/game.GameService/PlayTile"
	GameService_PassTurn_FullMethodName  = "/game.GameService/PassTurn"
	GameService_NextRound_FullMethodName = "/game.GameService/NextRound"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	PlayTile(ctx context.Context, in *PlayTileRequest, opts ...grpc.CallOption) (*PlayTileResponse, error)
	PassTurn(ctx context.Context, in *PassTurnRequest, opts ...grpc.CallOption) (*PassTurnResponse, error)
	NextRound(ctx context.Context, in *NextRoundRequest, opts ...grpc.CallOption) (*NextRoundResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) PlayTile(ctx context.Context, in *PlayTileRequest, opts ...grpc.CallOption) (*PlayTileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayTileResponse)
	err := c.cc.Invoke(ctx, GameService_PlayTile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) PassTurn(ctx context.Context, in *PassTurnRequest, opts ...grpc.CallOption) (*PassTurnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PassTurnResponse)
	err := c.cc.Invoke(ctx, GameService_PassTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) NextRound(ctx context.Context, in *NextRoundRequest, opts ...grpc.CallOption) (*NextRoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextRoundResponse)
	err := c.cc.Invoke(ctx, GameService_NextRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
type GameServiceServer interface {
	PlayTile(context.Context, *PlayTileRequest) (*PlayTileResponse, error)
	PassTurn(context.Context, *PassTurnRequest) (*PassTurnResponse, error)
	NextRound(context.Context, *NextRoundRequest) (*NextRoundResponse, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) PlayTile(context.Context, *PlayTileRequest) (*PlayTileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayTile not implemented")
}
func (UnimplementedGameServiceServer) PassTurn(context.Context, *PassTurnRequest) (*PassTurnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PassTurn not implemented")
}
func (UnimplementedGameServiceServer) NextRound(context.Context, *NextRoundRequest) (*NextRoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NextRound not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call panics, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_PlayTile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayTileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).PlayTile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_PlayTile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).PlayTile(ctx, req.(*PlayTileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_PassTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).PassTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_PassTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).PassTurn(ctx, req.(*PassTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_NextRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).NextRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_NextRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).NextRound(ctx, req.(*NextRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlayTile",
			Handler:    _GameService_PlayTile_Handler,
		},
		{
			MethodName: "PassTurn",
			Handler:    _GameService_PassTurn_Handler,
		},
		{
			MethodName: "NextRound",
			Handler:    _GameService_NextRound_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
