// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          int32                  `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	Right         int32                  `protobuf:"varint,2,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tile) Reset() {
	*x = Tile{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Tile) GetLeft() int32 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *Tile) GetRight() int32 {
	if x != nil {
		return x.Right
	}
	return 0
}

type PlayTileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tile          *Tile                  `protobuf:"bytes,3,opt,name=tile,proto3" json:"tile,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayTileRequest) Reset() {
	*x = PlayTileRequest{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayTileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayTileRequest) ProtoMessage() {}

func (x *PlayTileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayTileRequest.ProtoReflect.Descriptor instead.
func (*PlayTileRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayTileRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *PlayTileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayTileRequest) GetTile() *Tile {
	if x != nil {
		return x.Tile
	}
	return nil
}

func (x *PlayTileRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

type PlayTileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         []*Tile                `protobuf:"bytes,1,rep,name=board,proto3" json:"board,omitempty"`
	Hand          []*Tile                `protobuf:"bytes,2,rep,name=hand,proto3" json:"hand,omitempty"`
	RoundResult   *RoundResult           `protobuf:"bytes,3,opt,name=round_result,json=roundResult,proto3" json:"round_result,omitempty"` // this is optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayTileResponse) Reset() {
	*x = PlayTileResponse{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayTileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayTileResponse) ProtoMessage() {}

func (x *PlayTileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayTileResponse.ProtoReflect.Descriptor instead.
func (*PlayTileResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *PlayTileResponse) GetBoard() []*Tile {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *PlayTileResponse) GetHand() []*Tile {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *PlayTileResponse) GetRoundResult() *RoundResult {
	if x != nil {
		return x.RoundResult
	}
	return nil
}

type PassTurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassTurnRequest) Reset() {
	*x = PassTurnRequest{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassTurnRequest) ProtoMessage() {}

func (x *PassTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassTurnRequest.ProtoReflect.Descriptor instead.
func (*PassTurnRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *PassTurnRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *PassTurnRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PassTurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundResult   *RoundResult           `protobuf:"bytes,1,opt,name=round_result,json=roundResult,proto3" json:"round_result,omitempty"` // this is optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassTurnResponse) Reset() {
	*x = PassTurnResponse{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassTurnResponse) ProtoMessage() {}

func (x *PassTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassTurnResponse.ProtoReflect.Descriptor instead.
func (*PassTurnResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *PassTurnResponse) GetRoundResult() *RoundResult {
	if x != nil {
		return x.RoundResult
	}
	return nil
}

type NextRoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextRoundRequest) Reset() {
	*x = NextRoundRequest{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextRoundRequest) ProtoMessage() {}

func (x *NextRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextRoundRequest.ProtoReflect.Descriptor instead.
func (*NextRoundRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *NextRoundRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *NextRoundRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NextRoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber   int32                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextRoundResponse) Reset() {
	*x = NextRoundResponse{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextRoundResponse) ProtoMessage() {}

func (x *NextRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextRoundResponse.ProtoReflect.Descriptor instead.
func (*NextRoundResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *NextRoundResponse) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

type RoundResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinnerId      string                 `protobuf:"bytes,1,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                                                                                   // ReasonDomino | ReasonBlocked
	PipCounts     map[string]int32       `protobuf:"bytes,4,rep,name=pip_counts,json=pipCounts,proto3" json:"pip_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // map[TeamID] -> points
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundResult) Reset() {
	*x = RoundResult{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundResult) ProtoMessage() {}

func (x *RoundResult) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundResult.ProtoReflect.Descriptor instead.
func (*RoundResult) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *RoundResult) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

func (x *RoundResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RoundResult) GetPipCounts() map[string]int32 {
	if x != nil {
		return x.PipCounts
	}
	return nil
}

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tiles         []*Tile                `protobuf:"bytes,1,rep,name=tiles,proto3" json:"tiles,omitempty"` // already-oriented tiles, in play order
	LeftEnd       int32                  `protobuf:"varint,2,opt,name=left_end,json=leftEnd,proto3" json:"left_end,omitempty"`
	RightEnd      int32                  `protobuf:"varint,3,opt,name=right_end,json=rightEnd,proto3" json:"right_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *Board) GetTiles() []*Tile {
	if x != nil {
		return x.Tiles
	}
	return nil
}

func (x *Board) GetLeftEnd() int32 {
	if x != nil {
		return x.LeftEnd
	}
	return 0
}

func (x *Board) GetRightEnd() int32 {
	if x != nil {
		return x.RightEnd
	}
	return 0
}

type RemainingPips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tiles         []*Tile                `protobuf:"bytes,1,rep,name=tiles,proto3" json:"tiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemainingPips) Reset() {
	*x = RemainingPips{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemainingPips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemainingPips) ProtoMessage() {}

func (x *RemainingPips) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemainingPips.ProtoReflect.Descriptor instead.
func (*RemainingPips) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *RemainingPips) GetTiles() []*Tile {
	if x != nil {
		return x.Tiles
	}
	return nil
}

type GetGameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // caller — scopes which hand is visible
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateRequest) Reset() {
	*x = GetGameStateRequest{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateRequest) ProtoMessage() {}

func (x *GetGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateRequest.ProtoReflect.Descriptor instead.
func (*GetGameStateRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *GetGameStateRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *GetGameStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// NOTE: Should we send game like this? what happen when a spectator is added. What Tile hand?
type GetGameStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameNumber    int32                  `protobuf:"varint,2,opt,name=game_number,json=gameNumber,proto3" json:"game_number,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // GameStatus
	TeamScores    map[string]int32       `protobuf:"bytes,4,rep,name=team_scores,json=teamScores,proto3" json:"team_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TeamWinner    string                 `protobuf:"bytes,5,opt,name=team_winner,json=teamWinner,proto3" json:"team_winner,omitempty"`
	GoalScore     int32                  `protobuf:"varint,6,opt,name=goal_score,json=goalScore,proto3" json:"goal_score,omitempty"`
	RoundId       string                 `protobuf:"bytes,7,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	RoundNumber   int32                  `protobuf:"varint,8,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	RoundStatus   string                 `protobuf:"bytes,9,opt,name=round_status,json=roundStatus,proto3" json:"round_status,omitempty"` // RoundStatus
	PlayerOrder   []string               `protobuf:"bytes,10,rep,name=player_order,json=playerOrder,proto3" json:"player_order,omitempty"`
	CurrentTurn   string                 `protobuf:"bytes,11,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"`
	Board         *Board                 `protobuf:"bytes,12,opt,name=board,proto3" json:"board,omitempty"`
	Hand          []*Tile                `protobuf:"bytes,13,rep,name=hand,proto3" json:"hand,omitempty"`                                                                                                       // caller's own hand only
	HandSizes     map[string]int32       `protobuf:"bytes,14,rep,name=hand_sizes,json=handSizes,proto3" json:"hand_sizes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // every seat's remaining tile count
	RoundResult   *RoundResult           `protobuf:"bytes,15,opt,name=round_result,json=roundResult,proto3" json:"round_result,omitempty"`                                                                      // set only once round_status is ROUND_STATUS_OVER
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateResponse) Reset() {
	*x = GetGameStateResponse{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateResponse) ProtoMessage() {}

func (x *GetGameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateResponse.ProtoReflect.Descriptor instead.
func (*GetGameStateResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *GetGameStateResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GetGameStateResponse) GetGameNumber() int32 {
	if x != nil {
		return x.GameNumber
	}
	return 0
}

func (x *GetGameStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetGameStateResponse) GetTeamScores() map[string]int32 {
	if x != nil {
		return x.TeamScores
	}
	return nil
}

func (x *GetGameStateResponse) GetTeamWinner() string {
	if x != nil {
		return x.TeamWinner
	}
	return ""
}

func (x *GetGameStateResponse) GetGoalScore() int32 {
	if x != nil {
		return x.GoalScore
	}
	return 0
}

func (x *GetGameStateResponse) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *GetGameStateResponse) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *GetGameStateResponse) GetRoundStatus() string {
	if x != nil {
		return x.RoundStatus
	}
	return ""
}

func (x *GetGameStateResponse) GetPlayerOrder() []string {
	if x != nil {
		return x.PlayerOrder
	}
	return nil
}

func (x *GetGameStateResponse) GetCurrentTurn() string {
	if x != nil {
		return x.CurrentTurn
	}
	return ""
}

func (x *GetGameStateResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GetGameStateResponse) GetHand() []*Tile {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *GetGameStateResponse) GetHandSizes() map[string]int32 {
	if x != nil {
		return x.HandSizes
	}
	return nil
}

func (x *GetGameStateResponse) GetRoundResult() *RoundResult {
	if x != nil {
		return x.RoundResult
	}
	return nil
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"0\n" +
	"\x04Tile\x12\x12\n" +
	"\x04left\x18\x01 \x01(\x05R\x04left\x12\x14\n" +
	"\x05right\x18\x02 \x01(\x05R\x05right\"y\n" +
	"\x0fPlayTileRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\x04tile\x18\x03 \x01(\v2\n" +
	".game.TileR\x04tile\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\"\x8a\x01\n" +
	"\x10PlayTileResponse\x12 \n" +
	"\x05board\x18\x01 \x03(\v2\n" +
	".game.TileR\x05board\x12\x1e\n" +
	"\x04hand\x18\x02 \x03(\v2\n" +
	".game.TileR\x04hand\x124\n" +
	"\fround_result\x18\x03 \x01(\v2\x11.game.RoundResultR\vroundResult\"E\n" +
	"\x0fPassTurnRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x10PassTurnResponse\x124\n" +
	"\fround_result\x18\x01 \x01(\v2\x11.game.RoundResultR\vroundResult\"F\n" +
	"\x10NextRoundRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"6\n" +
	"\x11NextRoundResponse\x12!\n" +
	"\fround_number\x18\x01 \x01(\x05R\vroundNumber\"\xc1\x01\n" +
	"\vRoundResult\x12\x1b\n" +
	"\twinner_id\x18\x01 \x01(\tR\bwinnerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12?\n" +
	"\n" +
	"pip_counts\x18\x04 \x03(\v2 .game.RoundResult.PipCountsEntryR\tpipCounts\x1a<\n" +
	"\x0ePipCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"a\n" +
	"\x05Board\x12 \n" +
	"\x05tiles\x18\x01 \x03(\v2\n" +
	".game.TileR\x05tiles\x12\x19\n" +
	"\bleft_end\x18\x02 \x01(\x05R\aleftEnd\x12\x1b\n" +
	"\tright_end\x18\x03 \x01(\x05R\brightEnd\"1\n" +
	"\rRemainingPips\x12 \n" +
	"\x05tiles\x18\x01 \x03(\v2\n" +
	".game.TileR\x05tiles\"I\n" +
	"\x13GetGameStateRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xdc\x05\n" +
	"\x14GetGameStateResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1f\n" +
	"\vgame_number\x18\x02 \x01(\x05R\n" +
	"gameNumber\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12K\n" +
	"\vteam_scores\x18\x04 \x03(\v2*.game.GetGameStateResponse.TeamScoresEntryR\n" +
	"teamScores\x12\x1f\n" +
	"\vteam_winner\x18\x05 \x01(\tR\n" +
	"teamWinner\x12\x1d\n" +
	"\n" +
	"goal_score\x18\x06 \x01(\x05R\tgoalScore\x12\x19\n" +
	"\bround_id\x18\a \x01(\tR\aroundId\x12!\n" +
	"\fround_number\x18\b \x01(\x05R\vroundNumber\x12!\n" +
	"\fround_status\x18\t \x01(\tR\vroundStatus\x12!\n" +
	"\fplayer_order\x18\n" +
	" \x03(\tR\vplayerOrder\x12!\n" +
	"\fcurrent_turn\x18\v \x01(\tR\vcurrentTurn\x12!\n" +
	"\x05board\x18\f \x01(\v2\v.game.BoardR\x05board\x12\x1e\n" +
	"\x04hand\x18\r \x03(\v2\n" +
	".game.TileR\x04hand\x12H\n" +
	"\n" +
	"hand_sizes\x18\x0e \x03(\v2).game.GetGameStateResponse.HandSizesEntryR\thandSizes\x124\n" +
	"\fround_result\x18\x0f \x01(\v2\x11.game.RoundResultR\vroundResult\x1a=\n" +
	"\x0fTeamScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eHandSizesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\x88\x02\n" +
	"\vGameService\x129\n" +
	"\bPlayTile\x12\x15.game.PlayTileRequest\x1a\x16.game.PlayTileResponse\x129\n" +
	"\bPassTurn\x12\x15.game.PassTurnRequest\x1a\x16.game.PassTurnResponse\x12<\n" +
	"\tNextRound\x12\x16.game.NextRoundRequest\x1a\x17.game.NextRoundResponse\x12E\n" +
	"\fGetGameState\x12\x19.game.GetGameStateRequest\x1a\x1a.game.GetGameStateResponseB\x18Z\x16shared/proto/game;gameb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_game_proto_goTypes = []any{
	(*Tile)(nil),                 // 0: game.Tile
	(*PlayTileRequest)(nil),      // 1: game.PlayTileRequest
	(*PlayTileResponse)(nil),     // 2: game.PlayTileResponse
	(*PassTurnRequest)(nil),      // 3: game.PassTurnRequest
	(*PassTurnResponse)(nil),     // 4: game.PassTurnResponse
	(*NextRoundRequest)(nil),     // 5: game.NextRoundRequest
	(*NextRoundResponse)(nil),    // 6: game.NextRoundResponse
	(*RoundResult)(nil),          // 7: game.RoundResult
	(*Board)(nil),                // 8: game.Board
	(*RemainingPips)(nil),        // 9: game.RemainingPips
	(*GetGameStateRequest)(nil),  // 10: game.GetGameStateRequest
	(*GetGameStateResponse)(nil), // 11: game.GetGameStateResponse
	nil,                          // 12: game.RoundResult.PipCountsEntry
	nil,                          // 13: game.GetGameStateResponse.TeamScoresEntry
	nil,                          // 14: game.GetGameStateResponse.HandSizesEntry
}
var file_game_proto_depIdxs = []int32{
	0,  // 0: game.PlayTileRequest.tile:type_name -> game.Tile
	0,  // 1: game.PlayTileResponse.board:type_name -> game.Tile
	0,  // 2: game.PlayTileResponse.hand:type_name -> game.Tile
	7,  // 3: game.PlayTileResponse.round_result:type_name -> game.RoundResult
	7,  // 4: game.PassTurnResponse.round_result:type_name -> game.RoundResult
	12, // 5: game.RoundResult.pip_counts:type_name -> game.RoundResult.PipCountsEntry
	0,  // 6: game.Board.tiles:type_name -> game.Tile
	0,  // 7: game.RemainingPips.tiles:type_name -> game.Tile
	13, // 8: game.GetGameStateResponse.team_scores:type_name -> game.GetGameStateResponse.TeamScoresEntry
	8,  // 9: game.GetGameStateResponse.board:type_name -> game.Board
	0,  // 10: game.GetGameStateResponse.hand:type_name -> game.Tile
	14, // 11: game.GetGameStateResponse.hand_sizes:type_name -> game.GetGameStateResponse.HandSizesEntry
	7,  // 12: game.GetGameStateResponse.round_result:type_name -> game.RoundResult
	1,  // 13: game.GameService.PlayTile:input_type -> game.PlayTileRequest
	3,  // 14: game.GameService.PassTurn:input_type -> game.PassTurnRequest
	5,  // 15: game.GameService.NextRound:input_type -> game.NextRoundRequest
	10, // 16: game.GameService.GetGameState:input_type -> game.GetGameStateRequest
	2,  // 17: game.GameService.PlayTile:output_type -> game.PlayTileResponse
	4,  // 18: game.GameService.PassTurn:output_type -> game.PassTurnResponse
	6,  // 19: game.GameService.NextRound:output_type -> game.NextRoundResponse
	11, // 20: game.GameService.GetGameState:output_type -> game.GetGameStateResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
