syntax = "proto3";

package game;

option go_package = "shared/proto/game;game";

service GameService{
  rpc PlayTile(PlayTileRequest) returns (PlayTileResponse);
  rpc PassTurn(PassTurnRequest) returns (PassTurnResponse);
  rpc NextRound(NextRoundRequest) returns (NextRoundResponse);
}

message Tile{
  int32 left = 1;
  int32 right = 2;
}

message PlayTileRequest{
  string lobby_id = 1;
  string user_id = 2;
  Tile tile = 3;
  string side = 4;
}

message PlayTileResponse{
  repeated Tile board = 1;
  repeated Tile hand = 2;
  RoundResult round_result = 3; // this is optional
}

message PassTurnRequest{
  string lobby_id = 1;
  string user_id = 2;
}

message PassTurnResponse{
  RoundResult round_result = 1; // this is optional
}

message NextRoundRequest{
  string lobby_id = 1;
  string user_id = 2;
}

message NextRoundResponse{
  repeated Tile board = 1;
  repeated Tile hand = 2;
  RoundResult round_result = 3; // this is optional
}

message RoundResult {
  string winner_id  = 1;
  string reason  = 2;// ReasonDomino | ReasonBlocked
  map<string, int32 > scores = 3; // map[TeamID] -> points 
}




