syntax = "proto3";

package lobby;

option go_package = "shared/proto/lobby;lobby";

service LobbyService{
  rpc CreateLobby(CreateLobbyRequest) returns (CreateLobbyResponse);
  rpc JoinLobby(JoinLobbyRequest) returns (JoinLobbyResponse);
  rpc StartLobby(StartLobbyRequest) returns (StartLobbyResponse);
  rpc GetLobby(GetLobbyRequest) returns (GetLobbyResponse);
}

message CreateLobbyRequest{
  string userID = 1;
  int32 maxPlayers = 2;
}

message CreateLobbyResponse{
  Lobby lobby = 1;
}

message JoinLobbyRequest{
  string userID = 1;
  string lobbyID = 2;
  string secretCode = 3;
}

message JoinLobbyResponse{
  Lobby lobby = 1;
}

message StartLobbyRequest{
  string lobbyID = 1;
  string userID = 2;
}

message StartLobbyResponse{
}

message GetLobbyRequest{
  string lobbyID = 1;
}

message GetLobbyResponse{
  Lobby lobby = 1;
}

// Should I do something like returning a Lobby?
message Lobby{
  string id = 1;
  string hostId = 2;
  repeated Player players = 3;
  int32 maxPlayers = 4;
  LobbyStatus status = 5;
  LobbySettings settings = 6;
}

message Player{
  string id = 1;
  string name = 2;
  int32 slot = 3;
  bool isConnected = 4;
}

enum LobbyStatus{
  LOBBY_STATUS_WAITING = 0;
  LOBBY_STATUS_IN_GAME = 1;
  LOBBY_STATUS_FINISHED = 2;
}

message LobbySettings{
  int32 maxScore = 1;
  int32 turnTimerSeconds =2;
}
