// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: lobby.proto

package lobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LobbyStatus int32

const (
	LobbyStatus_LOBBY_STATUS_WAITING  LobbyStatus = 0
	LobbyStatus_LOBBY_STATUS_IN_GAME  LobbyStatus = 1
	LobbyStatus_LOBBY_STATUS_FINISHED LobbyStatus = 2
)

// Enum value maps for LobbyStatus.
var (
	LobbyStatus_name = map[int32]string{
		0: "LOBBY_STATUS_WAITING",
		1: "LOBBY_STATUS_IN_GAME",
		2: "LOBBY_STATUS_FINISHED",
	}
	LobbyStatus_value = map[string]int32{
		"LOBBY_STATUS_WAITING":  0,
		"LOBBY_STATUS_IN_GAME":  1,
		"LOBBY_STATUS_FINISHED": 2,
	}
)

func (x LobbyStatus) Enum() *LobbyStatus {
	p := new(LobbyStatus)
	*p = x
	return p
}

func (x LobbyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LobbyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[0].Descriptor()
}

func (LobbyStatus) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[0]
}

func (x LobbyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LobbyStatus.Descriptor instead.
func (LobbyStatus) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

type CreateLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,2,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	mi := &file_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLobbyRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CreateLobbyRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type CreateLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyResponse) Reset() {
	*x = CreateLobbyResponse{}
	mi := &file_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyResponse) ProtoMessage() {}

func (x *CreateLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateLobbyResponse) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLobbyResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type JoinLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	LobbyID       string                 `protobuf:"bytes,2,opt,name=lobbyID,proto3" json:"lobbyID,omitempty"`
	SecretCode    string                 `protobuf:"bytes,3,opt,name=secretCode,proto3" json:"secretCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyRequest) Reset() {
	*x = JoinLobbyRequest{}
	mi := &file_lobby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyRequest) ProtoMessage() {}

func (x *JoinLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyRequest.ProtoReflect.Descriptor instead.
func (*JoinLobbyRequest) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *JoinLobbyRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *JoinLobbyRequest) GetLobbyID() string {
	if x != nil {
		return x.LobbyID
	}
	return ""
}

func (x *JoinLobbyRequest) GetSecretCode() string {
	if x != nil {
		return x.SecretCode
	}
	return ""
}

type JoinLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,2,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyResponse) Reset() {
	*x = JoinLobbyResponse{}
	mi := &file_lobby_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyResponse) ProtoMessage() {}

func (x *JoinLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyResponse.ProtoReflect.Descriptor instead.
func (*JoinLobbyResponse) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *JoinLobbyResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyID       string                 `protobuf:"bytes,1,opt,name=lobbyID,proto3" json:"lobbyID,omitempty"`
	HostID        string                 `protobuf:"bytes,2,opt,name=hostID,proto3" json:"hostID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_lobby_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *StartGameRequest) GetLobbyID() string {
	if x != nil {
		return x.LobbyID
	}
	return ""
}

func (x *StartGameRequest) GetHostID() string {
	if x != nil {
		return x.HostID
	}
	return ""
}

type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameID        string                 `protobuf:"bytes,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_lobby_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{5}
}

func (x *StartGameResponse) GetGameID() string {
	if x != nil {
		return x.GameID
	}
	return ""
}

// Should I do something like returning a Lobby?
type Lobby struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=hostId,proto3" json:"hostId,omitempty"`
	SecretToken   string                 `protobuf:"bytes,3,opt,name=secretToken,proto3" json:"secretToken,omitempty"`
	WsURL         string                 `protobuf:"bytes,4,opt,name=wsURL,proto3" json:"wsURL,omitempty"`
	Players       []*Player              `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,6,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	Status        LobbyStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=lobby.LobbyStatus" json:"status,omitempty"`
	Settings      *LobbySettings         `protobuf:"bytes,8,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lobby) Reset() {
	*x = Lobby{}
	mi := &file_lobby_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lobby) ProtoMessage() {}

func (x *Lobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lobby.ProtoReflect.Descriptor instead.
func (*Lobby) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{6}
}

func (x *Lobby) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lobby) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Lobby) GetSecretToken() string {
	if x != nil {
		return x.SecretToken
	}
	return ""
}

func (x *Lobby) GetWsURL() string {
	if x != nil {
		return x.WsURL
	}
	return ""
}

func (x *Lobby) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Lobby) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *Lobby) GetStatus() LobbyStatus {
	if x != nil {
		return x.Status
	}
	return LobbyStatus_LOBBY_STATUS_WAITING
}

func (x *Lobby) GetSettings() *LobbySettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slot          int32                  `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_lobby_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{7}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type LobbySettings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaxScore         int32                  `protobuf:"varint,1,opt,name=maxScore,proto3" json:"maxScore,omitempty"`
	TurnTimerSeconds int32                  `protobuf:"varint,2,opt,name=turnTimerSeconds,proto3" json:"turnTimerSeconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LobbySettings) Reset() {
	*x = LobbySettings{}
	mi := &file_lobby_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbySettings) ProtoMessage() {}

func (x *LobbySettings) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbySettings.ProtoReflect.Descriptor instead.
func (*LobbySettings) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{8}
}

func (x *LobbySettings) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *LobbySettings) GetTurnTimerSeconds() int32 {
	if x != nil {
		return x.TurnTimerSeconds
	}
	return 0
}

var File_lobby_proto protoreflect.FileDescriptor

const file_lobby_proto_rawDesc = "" +
	"\n" +
	"\vlobby.proto\x12\x05lobby\"L\n" +
	"\x12CreateLobbyRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1e\n" +
	"\n" +
	"maxPlayers\x18\x02 \x01(\x05R\n" +
	"maxPlayers\"9\n" +
	"\x13CreateLobbyResponse\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby\"d\n" +
	"\x10JoinLobbyRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x18\n" +
	"\alobbyID\x18\x02 \x01(\tR\alobbyID\x12\x1e\n" +
	"\n" +
	"secretCode\x18\x03 \x01(\tR\n" +
	"secretCode\"7\n" +
	"\x11JoinLobbyResponse\x12\"\n" +
	"\x05lobby\x18\x02 \x01(\v2\f.lobby.LobbyR\x05lobby\"D\n" +
	"\x10StartGameRequest\x12\x18\n" +
	"\alobbyID\x18\x01 \x01(\tR\alobbyID\x12\x16\n" +
	"\x06hostID\x18\x02 \x01(\tR\x06hostID\"+\n" +
	"\x11StartGameResponse\x12\x16\n" +
	"\x06gameID\x18\x01 \x01(\tR\x06gameID\"\x8e\x02\n" +
	"\x05Lobby\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06hostId\x18\x02 \x01(\tR\x06hostId\x12 \n" +
	"\vsecretToken\x18\x03 \x01(\tR\vsecretToken\x12\x14\n" +
	"\x05wsURL\x18\x04 \x01(\tR\x05wsURL\x12'\n" +
	"\aplayers\x18\x05 \x03(\v2\r.lobby.PlayerR\aplayers\x12\x1e\n" +
	"\n" +
	"maxPlayers\x18\x06 \x01(\x05R\n" +
	"maxPlayers\x12*\n" +
	"\x06status\x18\a \x01(\x0e2\x12.lobby.LobbyStatusR\x06status\x120\n" +
	"\bsettings\x18\b \x01(\v2\x14.lobby.LobbySettingsR\bsettings\"@\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slot\x18\x03 \x01(\x05R\x04slot\"W\n" +
	"\rLobbySettings\x12\x1a\n" +
	"\bmaxScore\x18\x01 \x01(\x05R\bmaxScore\x12*\n" +
	"\x10turnTimerSeconds\x18\x02 \x01(\x05R\x10turnTimerSeconds*\\\n" +
	"\vLobbyStatus\x12\x18\n" +
	"\x14LOBBY_STATUS_WAITING\x10\x00\x12\x18\n" +
	"\x14LOBBY_STATUS_IN_GAME\x10\x01\x12\x19\n" +
	"\x15LOBBY_STATUS_FINISHED\x10\x022\xd4\x01\n" +
	"\fLobbyService\x12D\n" +
	"\vCreateLobby\x12\x19.lobby.CreateLobbyRequest\x1a\x1a.lobby.CreateLobbyResponse\x12>\n" +
	"\tJoinLobby\x12\x17.lobby.JoinLobbyRequest\x1a\x18.lobby.JoinLobbyResponse\x12>\n" +
	"\tStartGame\x12\x17.lobby.StartGameRequest\x1a\x18.lobby.StartGameResponseB\x1aZ\x18shared/proto/lobby;lobbyb\x06proto3"

var (
	file_lobby_proto_rawDescOnce sync.Once
	file_lobby_proto_rawDescData []byte
)

func file_lobby_proto_rawDescGZIP() []byte {
	file_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lobby_proto_rawDesc), len(file_lobby_proto_rawDesc)))
	})
	return file_lobby_proto_rawDescData
}

var file_lobby_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_lobby_proto_goTypes = []any{
	(LobbyStatus)(0),            // 0: lobby.LobbyStatus
	(*CreateLobbyRequest)(nil),  // 1: lobby.CreateLobbyRequest
	(*CreateLobbyResponse)(nil), // 2: lobby.CreateLobbyResponse
	(*JoinLobbyRequest)(nil),    // 3: lobby.JoinLobbyRequest
	(*JoinLobbyResponse)(nil),   // 4: lobby.JoinLobbyResponse
	(*StartGameRequest)(nil),    // 5: lobby.StartGameRequest
	(*StartGameResponse)(nil),   // 6: lobby.StartGameResponse
	(*Lobby)(nil),               // 7: lobby.Lobby
	(*Player)(nil),              // 8: lobby.Player
	(*LobbySettings)(nil),       // 9: lobby.LobbySettings
}
var file_lobby_proto_depIdxs = []int32{
	7, // 0: lobby.CreateLobbyResponse.lobby:type_name -> lobby.Lobby
	7, // 1: lobby.JoinLobbyResponse.lobby:type_name -> lobby.Lobby
	8, // 2: lobby.Lobby.players:type_name -> lobby.Player
	0, // 3: lobby.Lobby.status:type_name -> lobby.LobbyStatus
	9, // 4: lobby.Lobby.settings:type_name -> lobby.LobbySettings
	1, // 5: lobby.LobbyService.CreateLobby:input_type -> lobby.CreateLobbyRequest
	3, // 6: lobby.LobbyService.JoinLobby:input_type -> lobby.JoinLobbyRequest
	5, // 7: lobby.LobbyService.StartGame:input_type -> lobby.StartGameRequest
	2, // 8: lobby.LobbyService.CreateLobby:output_type -> lobby.CreateLobbyResponse
	4, // 9: lobby.LobbyService.JoinLobby:output_type -> lobby.JoinLobbyResponse
	6, // 10: lobby.LobbyService.StartGame:output_type -> lobby.StartGameResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_lobby_proto_init() }
func file_lobby_proto_init() {
	if File_lobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lobby_proto_rawDesc), len(file_lobby_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_proto_depIdxs,
		EnumInfos:         file_lobby_proto_enumTypes,
		MessageInfos:      file_lobby_proto_msgTypes,
	}.Build()
	File_lobby_proto = out.File
	file_lobby_proto_goTypes = nil
	file_lobby_proto_depIdxs = nil
}
