// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: history.proto

package history

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistoryService_GetRoundActions_FullMethodName = "/history.HistoryService/GetRoundActions"
	HistoryService_GetGameHistory_FullMethodName  = "/history.HistoryService/GetGameHistory"
	HistoryService_GetPlayerGames_FullMethodName  = "/history.HistoryService/GetPlayerGames"
)

// HistoryServiceClient is the client API for HistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryServiceClient interface {
	GetRoundActions(ctx context.Context, in *GetRoundActionsRequest, opts ...grpc.CallOption) (*GetRoundActionsResponse, error)
	GetGameHistory(ctx context.Context, in *GetGameHistoryRequest, opts ...grpc.CallOption) (*GetGameHistoryResponse, error)
	GetPlayerGames(ctx context.Context, in *GetPlayerGamesRequest, opts ...grpc.CallOption) (*GetPlayerGamesResponse, error)
}

type historyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryServiceClient(cc grpc.ClientConnInterface) HistoryServiceClient {
	return &historyServiceClient{cc}
}

func (c *historyServiceClient) GetRoundActions(ctx context.Context, in *GetRoundActionsRequest, opts ...grpc.CallOption) (*GetRoundActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoundActionsResponse)
	err := c.cc.Invoke(ctx, HistoryService_GetRoundActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetGameHistory(ctx context.Context, in *GetGameHistoryRequest, opts ...grpc.CallOption) (*GetGameHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameHistoryResponse)
	err := c.cc.Invoke(ctx, HistoryService_GetGameHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetPlayerGames(ctx context.Context, in *GetPlayerGamesRequest, opts ...grpc.CallOption) (*GetPlayerGamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerGamesResponse)
	err := c.cc.Invoke(ctx, HistoryService_GetPlayerGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServiceServer is the server API for HistoryService service.
// All implementations must embed UnimplementedHistoryServiceServer
// for forward compatibility.
type HistoryServiceServer interface {
	GetRoundActions(context.Context, *GetRoundActionsRequest) (*GetRoundActionsResponse, error)
	GetGameHistory(context.Context, *GetGameHistoryRequest) (*GetGameHistoryResponse, error)
	GetPlayerGames(context.Context, *GetPlayerGamesRequest) (*GetPlayerGamesResponse, error)
	mustEmbedUnimplementedHistoryServiceServer()
}

// UnimplementedHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistoryServiceServer struct{}

func (UnimplementedHistoryServiceServer) GetRoundActions(context.Context, *GetRoundActionsRequest) (*GetRoundActionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoundActions not implemented")
}
func (UnimplementedHistoryServiceServer) GetGameHistory(context.Context, *GetGameHistoryRequest) (*GetGameHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameHistory not implemented")
}
func (UnimplementedHistoryServiceServer) GetPlayerGames(context.Context, *GetPlayerGamesRequest) (*GetPlayerGamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerGames not implemented")
}
func (UnimplementedHistoryServiceServer) mustEmbedUnimplementedHistoryServiceServer() {}
func (UnimplementedHistoryServiceServer) testEmbeddedByValue()                        {}

// UnsafeHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryServiceServer will
// result in compilation errors.
type UnsafeHistoryServiceServer interface {
	mustEmbedUnimplementedHistoryServiceServer()
}

func RegisterHistoryServiceServer(s grpc.ServiceRegistrar, srv HistoryServiceServer) {
	// If the following call panics, it indicates UnimplementedHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistoryService_ServiceDesc, srv)
}

func _HistoryService_GetRoundActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoundActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetRoundActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetRoundActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetRoundActions(ctx, req.(*GetRoundActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetGameHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetGameHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetGameHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetGameHistory(ctx, req.(*GetGameHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetPlayerGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetPlayerGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetPlayerGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetPlayerGames(ctx, req.(*GetPlayerGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HistoryService_ServiceDesc is the grpc.ServiceDesc for HistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "history.HistoryService",
	HandlerType: (*HistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoundActions",
			Handler:    _HistoryService_GetRoundActions_Handler,
		},
		{
			MethodName: "GetGameHistory",
			Handler:    _HistoryService_GetGameHistory_Handler,
		},
		{
			MethodName: "GetPlayerGames",
			Handler:    _HistoryService_GetPlayerGames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "history.proto",
}
