// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: history.proto

package history

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          int32                  `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	Right         int32                  `protobuf:"varint,2,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tile) Reset() {
	*x = Tile{}
	mi := &file_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{0}
}

func (x *Tile) GetLeft() int32 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *Tile) GetRight() int32 {
	if x != nil {
		return x.Right
	}
	return 0
}

type GetRoundActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=roundId,proto3" json:"roundId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoundActionsRequest) Reset() {
	*x = GetRoundActionsRequest{}
	mi := &file_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoundActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoundActionsRequest) ProtoMessage() {}

func (x *GetRoundActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoundActionsRequest.ProtoReflect.Descriptor instead.
func (*GetRoundActionsRequest) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoundActionsRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

type Action struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActionNumber      int32                  `protobuf:"varint,1,opt,name=actionNumber,proto3" json:"actionNumber,omitempty"`
	PlayerId          string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	ActionType        string                 `protobuf:"bytes,3,opt,name=actionType,proto3" json:"actionType,omitempty"` // "play" | "pass"
	Tile              *Tile                  `protobuf:"bytes,4,opt,name=tile,proto3" json:"tile,omitempty"`             // unset when actionType == "pass"
	Side              string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	ResultingLeftEnd  int32                  `protobuf:"varint,6,opt,name=resultingLeftEnd,proto3" json:"resultingLeftEnd,omitempty"`
	ResultingRightEnd int32                  `protobuf:"varint,7,opt,name=resultingRightEnd,proto3" json:"resultingRightEnd,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{2}
}

func (x *Action) GetActionNumber() int32 {
	if x != nil {
		return x.ActionNumber
	}
	return 0
}

func (x *Action) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Action) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *Action) GetTile() *Tile {
	if x != nil {
		return x.Tile
	}
	return nil
}

func (x *Action) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Action) GetResultingLeftEnd() int32 {
	if x != nil {
		return x.ResultingLeftEnd
	}
	return 0
}

func (x *Action) GetResultingRightEnd() int32 {
	if x != nil {
		return x.ResultingRightEnd
	}
	return 0
}

type Hand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Tiles         []*Tile                `protobuf:"bytes,2,rep,name=tiles,proto3" json:"tiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hand) Reset() {
	*x = Hand{}
	mi := &file_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hand) ProtoMessage() {}

func (x *Hand) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hand.ProtoReflect.Descriptor instead.
func (*Hand) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{3}
}

func (x *Hand) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Hand) GetTiles() []*Tile {
	if x != nil {
		return x.Tiles
	}
	return nil
}

type GetRoundActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	Hands         []*Hand                `protobuf:"bytes,2,rep,name=hands,proto3" json:"hands,omitempty"` // initial dealt hands, enough (with actions) to replay the round
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoundActionsResponse) Reset() {
	*x = GetRoundActionsResponse{}
	mi := &file_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoundActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoundActionsResponse) ProtoMessage() {}

func (x *GetRoundActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoundActionsResponse.ProtoReflect.Descriptor instead.
func (*GetRoundActionsResponse) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoundActionsResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *GetRoundActionsResponse) GetHands() []*Hand {
	if x != nil {
		return x.Hands
	}
	return nil
}

type GetGameHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameHistoryRequest) Reset() {
	*x = GetGameHistoryRequest{}
	mi := &file_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameHistoryRequest) ProtoMessage() {}

func (x *GetGameHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetGameHistoryRequest) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{5}
}

func (x *GetGameHistoryRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type RoundSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RoundId          string                 `protobuf:"bytes,1,opt,name=roundId,proto3" json:"roundId,omitempty"`
	RoundNumber      int32                  `protobuf:"varint,2,opt,name=roundNumber,proto3" json:"roundNumber,omitempty"`
	StartingPlayerId string                 `protobuf:"bytes,3,opt,name=startingPlayerId,proto3" json:"startingPlayerId,omitempty"`
	WinnerTeamId     string                 `protobuf:"bytes,4,opt,name=winnerTeamId,proto3" json:"winnerTeamId,omitempty"`
	Reason           string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                                                                            // ReasonDomino | ReasonBlocked
	Scores           map[string]int32       `protobuf:"bytes,6,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // map[TeamID] -> score (sum of tiles for that round)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RoundSummary) Reset() {
	*x = RoundSummary{}
	mi := &file_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundSummary) ProtoMessage() {}

func (x *RoundSummary) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundSummary.ProtoReflect.Descriptor instead.
func (*RoundSummary) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{6}
}

func (x *RoundSummary) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *RoundSummary) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *RoundSummary) GetStartingPlayerId() string {
	if x != nil {
		return x.StartingPlayerId
	}
	return ""
}

func (x *RoundSummary) GetWinnerTeamId() string {
	if x != nil {
		return x.WinnerTeamId
	}
	return ""
}

func (x *RoundSummary) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RoundSummary) GetScores() map[string]int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

type GetGameHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rounds        []*RoundSummary        `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameHistoryResponse) Reset() {
	*x = GetGameHistoryResponse{}
	mi := &file_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameHistoryResponse) ProtoMessage() {}

func (x *GetGameHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetGameHistoryResponse) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{7}
}

func (x *GetGameHistoryResponse) GetRounds() []*RoundSummary {
	if x != nil {
		return x.Rounds
	}
	return nil
}

type GetPlayerGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerGamesRequest) Reset() {
	*x = GetPlayerGamesRequest{}
	mi := &file_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerGamesRequest) ProtoMessage() {}

func (x *GetPlayerGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerGamesRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerGamesRequest) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{8}
}

func (x *GetPlayerGamesRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetPlayerGamesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPlayerGamesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GameSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	LobbyId       string                 `protobuf:"bytes,2,opt,name=lobbyId,proto3" json:"lobbyId,omitempty"`
	FinalScores   map[string]int32       `protobuf:"bytes,3,rep,name=finalScores,proto3" json:"finalScores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // map[TeamID] -> points
	TeamWinner    string                 `protobuf:"bytes,4,opt,name=teamWinner,proto3" json:"teamWinner,omitempty"`
	GameState     string                 `protobuf:"bytes,5,opt,name=gameState,proto3" json:"gameState,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSummary) Reset() {
	*x = GameSummary{}
	mi := &file_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSummary) ProtoMessage() {}

func (x *GameSummary) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSummary.ProtoReflect.Descriptor instead.
func (*GameSummary) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{9}
}

func (x *GameSummary) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameSummary) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *GameSummary) GetFinalScores() map[string]int32 {
	if x != nil {
		return x.FinalScores
	}
	return nil
}

func (x *GameSummary) GetTeamWinner() string {
	if x != nil {
		return x.TeamWinner
	}
	return ""
}

func (x *GameSummary) GetGameState() string {
	if x != nil {
		return x.GameState
	}
	return ""
}

func (x *GameSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetPlayerGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*GameSummary         `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerGamesResponse) Reset() {
	*x = GetPlayerGamesResponse{}
	mi := &file_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerGamesResponse) ProtoMessage() {}

func (x *GetPlayerGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerGamesResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerGamesResponse) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlayerGamesResponse) GetGames() []*GameSummary {
	if x != nil {
		return x.Games
	}
	return nil
}

var File_history_proto protoreflect.FileDescriptor

const file_history_proto_rawDesc = "" +
	"\n" +
	"\rhistory.proto\x12\ahistory\"0\n" +
	"\x04Tile\x12\x12\n" +
	"\x04left\x18\x01 \x01(\x05R\x04left\x12\x14\n" +
	"\x05right\x18\x02 \x01(\x05R\x05right\"2\n" +
	"\x16GetRoundActionsRequest\x12\x18\n" +
	"\aroundId\x18\x01 \x01(\tR\aroundId\"\xf9\x01\n" +
	"\x06Action\x12\"\n" +
	"\factionNumber\x18\x01 \x01(\x05R\factionNumber\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\x12\x1e\n" +
	"\n" +
	"actionType\x18\x03 \x01(\tR\n" +
	"actionType\x12!\n" +
	"\x04tile\x18\x04 \x01(\v2\r.history.TileR\x04tile\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12*\n" +
	"\x10resultingLeftEnd\x18\x06 \x01(\x05R\x10resultingLeftEnd\x12,\n" +
	"\x11resultingRightEnd\x18\a \x01(\x05R\x11resultingRightEnd\"G\n" +
	"\x04Hand\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12#\n" +
	"\x05tiles\x18\x02 \x03(\v2\r.history.TileR\x05tiles\"i\n" +
	"\x17GetRoundActionsResponse\x12)\n" +
	"\aactions\x18\x01 \x03(\v2\x0f.history.ActionR\aactions\x12#\n" +
	"\x05hands\x18\x02 \x03(\v2\r.history.HandR\x05hands\"/\n" +
	"\x15GetGameHistoryRequest\x12\x16\n" +
	"\x06gameId\x18\x01 \x01(\tR\x06gameId\"\xa8\x02\n" +
	"\fRoundSummary\x12\x18\n" +
	"\aroundId\x18\x01 \x01(\tR\aroundId\x12 \n" +
	"\vroundNumber\x18\x02 \x01(\x05R\vroundNumber\x12*\n" +
	"\x10startingPlayerId\x18\x03 \x01(\tR\x10startingPlayerId\x12\"\n" +
	"\fwinnerTeamId\x18\x04 \x01(\tR\fwinnerTeamId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x129\n" +
	"\x06scores\x18\x06 \x03(\v2!.history.RoundSummary.ScoresEntryR\x06scores\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"G\n" +
	"\x16GetGameHistoryResponse\x12-\n" +
	"\x06rounds\x18\x01 \x03(\v2\x15.history.RoundSummaryR\x06rounds\"a\n" +
	"\x15GetPlayerGamesRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xa4\x02\n" +
	"\vGameSummary\x12\x16\n" +
	"\x06gameId\x18\x01 \x01(\tR\x06gameId\x12\x18\n" +
	"\alobbyId\x18\x02 \x01(\tR\alobbyId\x12G\n" +
	"\vfinalScores\x18\x03 \x03(\v2%.history.GameSummary.FinalScoresEntryR\vfinalScores\x12\x1e\n" +
	"\n" +
	"teamWinner\x18\x04 \x01(\tR\n" +
	"teamWinner\x12\x1c\n" +
	"\tgameState\x18\x05 \x01(\tR\tgameState\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\tR\tcreatedAt\x1a>\n" +
	"\x10FinalScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"D\n" +
	"\x16GetPlayerGamesResponse\x12*\n" +
	"\x05games\x18\x01 \x03(\v2\x14.history.GameSummaryR\x05games2\x8c\x02\n" +
	"\x0eHistoryService\x12T\n" +
	"\x0fGetRoundActions\x12\x1f.history.GetRoundActionsRequest\x1a .history.GetRoundActionsResponse\x12Q\n" +
	"\x0eGetGameHistory\x12\x1e.history.GetGameHistoryRequest\x1a\x1f.history.GetGameHistoryResponse\x12Q\n" +
	"\x0eGetPlayerGames\x12\x1e.history.GetPlayerGamesRequest\x1a\x1f.history.GetPlayerGamesResponseB\x1eZ\x1cshared/proto/history;historyb\x06proto3"

var (
	file_history_proto_rawDescOnce sync.Once
	file_history_proto_rawDescData []byte
)

func file_history_proto_rawDescGZIP() []byte {
	file_history_proto_rawDescOnce.Do(func() {
		file_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_history_proto_rawDesc), len(file_history_proto_rawDesc)))
	})
	return file_history_proto_rawDescData
}

var file_history_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_history_proto_goTypes = []any{
	(*Tile)(nil),                    // 0: history.Tile
	(*GetRoundActionsRequest)(nil),  // 1: history.GetRoundActionsRequest
	(*Action)(nil),                  // 2: history.Action
	(*Hand)(nil),                    // 3: history.Hand
	(*GetRoundActionsResponse)(nil), // 4: history.GetRoundActionsResponse
	(*GetGameHistoryRequest)(nil),   // 5: history.GetGameHistoryRequest
	(*RoundSummary)(nil),            // 6: history.RoundSummary
	(*GetGameHistoryResponse)(nil),  // 7: history.GetGameHistoryResponse
	(*GetPlayerGamesRequest)(nil),   // 8: history.GetPlayerGamesRequest
	(*GameSummary)(nil),             // 9: history.GameSummary
	(*GetPlayerGamesResponse)(nil),  // 10: history.GetPlayerGamesResponse
	nil,                             // 11: history.RoundSummary.ScoresEntry
	nil,                             // 12: history.GameSummary.FinalScoresEntry
}
var file_history_proto_depIdxs = []int32{
	0,  // 0: history.Action.tile:type_name -> history.Tile
	0,  // 1: history.Hand.tiles:type_name -> history.Tile
	2,  // 2: history.GetRoundActionsResponse.actions:type_name -> history.Action
	3,  // 3: history.GetRoundActionsResponse.hands:type_name -> history.Hand
	11, // 4: history.RoundSummary.scores:type_name -> history.RoundSummary.ScoresEntry
	6,  // 5: history.GetGameHistoryResponse.rounds:type_name -> history.RoundSummary
	12, // 6: history.GameSummary.finalScores:type_name -> history.GameSummary.FinalScoresEntry
	9,  // 7: history.GetPlayerGamesResponse.games:type_name -> history.GameSummary
	1,  // 8: history.HistoryService.GetRoundActions:input_type -> history.GetRoundActionsRequest
	5,  // 9: history.HistoryService.GetGameHistory:input_type -> history.GetGameHistoryRequest
	8,  // 10: history.HistoryService.GetPlayerGames:input_type -> history.GetPlayerGamesRequest
	4,  // 11: history.HistoryService.GetRoundActions:output_type -> history.GetRoundActionsResponse
	7,  // 12: history.HistoryService.GetGameHistory:output_type -> history.GetGameHistoryResponse
	10, // 13: history.HistoryService.GetPlayerGames:output_type -> history.GetPlayerGamesResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_history_proto_init() }
func file_history_proto_init() {
	if File_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_history_proto_rawDesc), len(file_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_history_proto_goTypes,
		DependencyIndexes: file_history_proto_depIdxs,
		MessageInfos:      file_history_proto_msgTypes,
	}.Build()
	File_history_proto = out.File
	file_history_proto_goTypes = nil
	file_history_proto_depIdxs = nil
}
