apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lobby-service
  template:
    metadata:
      labels:
        app: lobby-service
    spec:
      containers:
        - name: lobby-service
          image: domino/lobby-service
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: uri
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: uri
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: JAEGER_ENDPOINT
                  name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: lobby-service
spec:
  selector:
    app: lobby-service
  ports:
    - port: 9092
      name: grpc
      targetPort: 9092
  type: ClusterIP

