
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  username: "guest"
  password: "guest"
  uri: "amqp://guest:guest@rabbitmq:5672/"
---
apiVersion: v1
kind: Secret
metadata:
  name: external-apis
type: Opaque
stringData:
  osrm: "http://router.project-osrm.org"
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
type: Opaque
stringData:
  stripe-secret-key: "sk_test_51Ti8UiDawE7kXBTKShq9EAd2fmoZjn8eCJkmU6RNKseWovm1S5WanU3yRvMXsvrqXgooVpJWayGl7QZ5MwwjvNW400esa2ffaR"
  stripe-webhook-key: "whsec_91295ea5c355c6eb60ef62c7b2cb22fca3e1dec34e56a790eb2e739339a3cdfe"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
stringData:
  uri: "mongodb+srv://rebu-app:YourActualPassword@cluster0.ubuy0oe.mongodb.net/?appName=Cluster0"
